### ISSUE TITLE
Run a method from app2 that uses webassembly to crunch large numbers

### ISSUE THREAD

**Issue by jankapunkt** [shahin4u000/Meteor-communication-between-two-app-through-ddp#6]
This task requires #5 to be done first.

The goal is to let the logged in user of app2 to call a method in app1. The method in app1 should [compute the faculty of a given numbe](https://stackoverflow.com/questions/3959211/fast-factorial-function-in-javascript)r that is sent by app2.

# Part I  - remote method call

**App1**

- [ ]  create a [Meteor method](https://guide.meteor.com/methods.html) that **does not use webassembly but javascript** to compute the faculty of a given number

- [ ] the function should throw an error if the input is invalid or the method is not called by a logged in user

**App2**

- [ ]  create a simple input field using `AutoForm` that requires to input a number. When the form is sent, the number should be used as input parameter for the Method call to app1. Call the method of app1 and display the result.

# Part II - Include Webassembly execution

- [ ]  read first on how to integrate webassembly in [nodejs](https://github.com/nodejs/node/issues/16952) and check if your `meteor node`  command lets you run `WebAssembly.compile`

- [ ]  use webassembly studio (or whatever development environment you want to use) and create the factorial function that is compiled into webassembly. 

- [ ] Create a second Meteor method in app1 that can be called by app2 and which takes again the argument (Number) and calls the webassembly code  to execute the factorial function. Call it from app2 and display the result in app2

- [ ] Congratulations, when you are at this point you already solved a big issue here. Now we finally want to see a comparison of the performance of both methods ([use a package to do that](https://www.npmjs.com/package/performance-now)). In order to do that, you may add timers to your method call and compare the time used by each method (JS vs WASM) in order to calculate the factorial function. Compare small numbers with bigger numbers.
